name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your preferred version

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build React application
        run: cd frontend && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action will deploy to.
          FOLDER: frontend/docs # The folder where your static files are located.
          CLEAN: true # Automatically remove deleted files from the deploy branch