name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your preferred version

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build React application
        run: cd frontend && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: frontend/docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2